site_name: Ethics in Modern Society
site_description: 'Ethical issues and considerations in modern society backed by critical thinking and data science.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/ethics-course/'
repo_url: 'https://github.com/dmccreary/ethics-course'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - course-description.md
  - Outline: outline.md
  - Chapters:
    - "1. Introduction": chapters/01-introduction/index.md
    - "2. Measuring Harm": chapters/02-measuring-harm/index.md
    - "2.1 Rankings": chapters/02-measuring-harm/ranking.md
    - "2.2 Scorecard": chapters/02-measuring-harm/scorecard.md
    - "3. Data Gathering": chapters/03-data-gathering/index.md
    - "4. Impact Analysis": chapters/04-impact-analysis/index.md
    - "5. Systems Thinking": chapters/05-systems-thinking/index.md
    - "6. Looking for Leverage": chapters/06-looking-for-leverage/index.md
    - "7. Advocating for Change": chapters/07-advocating-for-change/index.md
    - "8. Capstone Project": chapters/08-capstone-project/index.md
  - Micro Simulations:
    - "Ranking Simulation": sims/ranking/index.md
  - Generative AI Prompts:
    - Intro: prompts/index.md
    - prompts/learning-graph/01-course-description.md
    - prompts/learning-graph/02-concept-enumeration.md
    - prompts/learning-graph/03-concept-dependencies.md
  - Glossary: glossary.md
  - References: references.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
  - social_override
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX